<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SIASUN.RCS.Adapters.Passbox</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\02.Domain\SIASUN.RCS.Domain\SIASUN.RCS.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Core" Version="10.5.0" />
  </ItemGroup>

</Project>
