<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SIASUN.RCS.Infrastructure.Logging</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\02.Domain\SIASUN.RCS.Domain\SIASUN.RCS.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- 零 LOH 内存流池 -->
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <!-- Serilog CLEF 紧凑格式化与异步 -->
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <!-- ABP 核心基础模块 -->
    <PackageReference Include="Volo.Abp.Core" Version="10.5.0" />
  </ItemGroup>

</Project>
