<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SIASUN.RCS</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\05.Infrastructure\SIASUN.RCS.EntityFrameworkCore\SIASUN.RCS.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\03.Application\SIASUN.RCS.Application.Contracts\SIASUN.RCS.Application.Contracts.csproj" />
    <ProjectReference Include="..\SIASUN.RCS.Application.Tests\SIASUN.RCS.Application.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="10.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

</Project>
